import { Inter,  Fjalla_One} from "next/font/google";
import "./styles/globals.css";
import { LanguageProvider } from "./hooks/LanguageContext";

// const inter = Inter({ subsets: ["latin"] });
const anton = Fjalla_One({ preload: true, subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Marucci Official Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={anton.className}>
      <LanguageProvider>
        {children}
      </LanguageProvider>
    </body>
    </html>
  );
}
